### ISSUE TITLE
"font table updating 100%" stuck screen and board

### ISSUE THREAD

**Issue by Bergateo** [makerbase-mks/MKS-Robin-Nano-S-Firmware#3]
Hi everyone! after I've receved my 3d printer (flyingbear ghost 5) i've tried to upload your marlin firmware but now the board is stuck on that error (font table booting 100%) and doesn't respond or recover after hours of wait...
Here there the list of the things I've already tried out:

  -  to plug off and reinstall the same fw,
  -  to install the old one that was working,
  -  try another version dowload from an italian repository (but i think it was the same as yours)
  -  tried out other different fw
  -  format the ft card to fat32 and try again
  -  tried out different sd cards
  -  But nothing works, the screen stays on the same error.

i think it's a problem in eleborating/reading files in the ft card...
i would like to try out an arduino or an AVR to force the fw into it or, maybe more simply, to reset to factory data but since i'm not able to do it, i would like to know if is possible and if it is, to kindly have a guide to do it?

**Comment by mks-viva** [comment]
Can you try to it: https://github.com/mks-viva/Marlin/tree/bugfix-2.0.x
This firmware already supports MKS Robin Nano V1.3 and Nano-S V1.3 board 
MKS Robin Nano V1.2 : MCU is STM32F103VET6
MKS Robin Nano V1.3 and Nano-S V1.3: MCU is STM32F407VET6
So, you does't update V1.2 version firmware to V1.3 board

**Comment by Bergateo** [comment]
Just tried out but the board isn't founding the .bin file created on visual studio in the SD card when powered on...

**Comment by whhx-open** [comment]
@Bergateo Which firmware has been flashed, this error will appear, can you tell me the download link?

**Comment by Bergateo** [comment]
> 
> 
> @Bergateo Which firmware has been flashed, this error will appear, can you tell me the download link?

Hi! the first one that ended in this was this repository from the italian club for flyingbear ghost https://github.com/flyingbear-club-ita/mks-robin-nano-1.x and they are reporting the ones from the official channel of flyingbear.
However i've download and tried to install the ghost_5_base and from that point i coudn't use the upload procedure for any fw
tried

**Comment by whhx-open** [comment]
![image](https://user-images.githubusercontent.com/14251428/133070061-9ec20397-5051-47aa-94cb-4e15a0fcc200.png)
You mean that after you update this firmware, you cannot update another firmware, is that right?

**Comment by Bergateo** [comment]
> ![image](https://user-images.githubusercontent.com/14251428/133070061-9ec20397-5051-47aa-94cb-4e15a0fcc200.png)
> You mean that after you update this firmware, you cannot update another firmware, is that right?

Exactly, is that firmware and from that is stuck

**Comment by Bergateo** [comment]
> 
> 
> Can you try to it: https://github.com/mks-viva/Marlin/tree/bugfix-2.0.x
> This firmware already supports MKS Robin Nano V1.3 and Nano-S V1.3 board
> MKS Robin Nano V1.2 : MCU is STM32F103VET6
> MKS Robin Nano V1.3 and Nano-S V1.3: MCU is STM32F407VET6
> So, you does't update V1.2 version firmware to V1.3 board

i'm trying to compile correctly the files but if I put any of the TFT nano screen (i've tryed all of them), the compiler fails and does not create the files...

**Comment by mks-viva** [comment]
> > Can you try to it: https://github.com/mks-viva/Marlin/tree/bugfix-2.0.x
> > This firmware already supports MKS Robin Nano V1.3 and Nano-S V1.3 board
> > MKS Robin Nano V1.2 : MCU is STM32F103VET6
> > MKS Robin Nano V1.3 and Nano-S V1.3: MCU is STM32F407VET6
> > So, you does't update V1.2 version firmware to V1.3 board
> 
> i'm trying to compile correctly the files but if I put any of the TFT nano screen (i've tryed all of them), the compiler fails and does not create the files...

Can't update?

**Comment by Bergateo** [comment]
> > > Can you try to it: https://github.com/mks-viva/Marlin/tree/bugfix-2.0.x
> > > This firmware already supports MKS Robin Nano V1.3 and Nano-S V1.3 board
> > > MKS Robin Nano V1.2 : MCU is STM32F103VET6
> > > MKS Robin Nano V1.3 and Nano-S V1.3: MCU is STM32F407VET6
> > > So, you does't update V1.2 version firmware to V1.3 board
> > 
> > i'm trying to compile correctly the files but if I put any of the TFT nano screen (i've tryed all of them), the compiler fails and does not create the files...
> 
> Can't update?

No because I'm missing the assets folder, but I think that even if I could get it, it wouldn't work because I've already tried out other version, but the board don't see the marlin fw, just the "original"

**Comment by Bergateo** [comment]
> > > > Can you try to it: https://github.com/mks-viva/Marlin/tree/bugfix-2.0.x
> > > > This firmware already supports MKS Robin Nano V1.3 and Nano-S V1.3 board
> > > > MKS Robin Nano V1.2 : MCU is STM32F103VET6
> > > > MKS Robin Nano V1.3 and Nano-S V1.3: MCU is STM32F407VET6
> > > > So, you does't update V1.2 version firmware to V1.3 board
> > > 
> > > i'm trying to compile correctly the files but if I put any of the TFT nano screen (i've tryed all of them), the compiler fails and does not create the files...
> > 
> > Can't update?
> 
> No because I'm missing the assets folder, but I think that even if I could get it, it wouldn't work because I've already tried out other version, but the board don't see the marlin fw, the printer boot without seeing the fw, like there's no sd.. It see just the "original" files..
If you want I uploaded on YouTube 2 videos to show to banggood the problem, I'll link them here

**Comment by Bergateo** [comment]
https://youtu.be/bAIZL_10I_w
https://youtube.com/shorts/OF_6f95Sg4s?feature=share

**Comment by Bergateo** [comment]
but if i use the plugin of visual studio "auto build marlin" and configure the configuration.h file correctly having also the assets folder, can I directly upload to the board with the usb cable since if i connect the board is detected? 
i've tried to use pronterface but it can't connect to the printer even if it detects the right port...

**Comment by mks-viva** [comment]
May be need reupload bootloader firmware to the motherboard.

**Comment by Bergateo** [comment]
I think it too but there's no bootloader for the Nano S 1.3.. Should I use the one for the Nano v1.3? And how should I upload it? there is a guide?

**Comment by mks-viva** [comment]
Hi! You can refer to here: https://github.com/makerbase-mks/MKS-Robin-Nano-V1.X/tree/master/Bootloader

**Comment by Bergateo** [comment]
i'll buy it and should arrive tomorrow but i cannot find where the pins should be connected, because i cannot find the pin for the 3.3v on the st-link...
so to be clear:
pin1 (of MKS): PA13 (pin7 of st-link)
pin2: 3.3 (pin?) 
pin3: PA14 (pin 9)
pin4: GND (pin 4)
pin5: RST (pin 15)
pin6: GND (pin 6)
are they right? (i'm refearring to this image https://stm32-base.org/assets/img/pinouts/ST-LINK_V2_Official_Header.png )

**Comment by mks-viva** [comment]
Is right. You can disconnect 3.3V, but you need connect DC12-24V to power input

**Comment by Bergateo** [comment]
Ok perfect than, I will try in the next days

**Comment by Bergateo** [comment]
i've found out that the pin 19 of the st-link is a 5v output pin; tomorrow, when the st-link arrives, i'll try to connect the output voltage to the board and if doesn't work, i'll just provide to the board the 12v from the electric socket and disconnect the pin 19

**Comment by Bergateo** [comment]
i've connected everything, the st-link v2 is detected from the j-flash program but is not connecting to the target... i've also tried with and without the 12v power... i've followed your instrution on the .txt file to do the connection but nothing works... any idea on how can i fix it?

**Comment by Bergateo** [comment]
This is how I connected everything to the st-link![IMG_20210916_170437.jpg](https://user-images.githubusercontent.com/67469499/133637331-9443d543-ecbb-4251-9af6-2fc9423964e6.jpg)

actually the program does recognize the chip version if I connect the st-link, but when i hit the connect button, it says that cannot connect to it... i've also noticed that if I plug the board to the 12v the screen stays black and sometimes if i reset it, it turns on with the "booting" screen... I hope i've been clear
(by the way the program that i'm using is "stm32 st-link utility", because the j-flash program doesn't recognize the st-link)

**Comment by Bergateo** [comment]
this is the error of j-link:
![screen j-flash error](https://user-images.githubusercontent.com/67469499/133644570-69f90598-7794-4f24-8edd-49add1597440.jpeg)

and this is the error from st-link utility
![st-link utility screen error](https://user-images.githubusercontent.com/67469499/133648434-0d413d12-c9a0-44ec-96a8-2f5a49dcce26.jpeg)

and this is the wire diagram:
(on the left the MKS pin, on the right the st-link pins)
1 ----- 7
2 ----- 1
3 ----- 9
4 ----- 8
5 ----- 15
6 ----- 20
it seems like the board is not comunicating with the ts-link... even thogh is getting power (the red led is turned on)

**Comment by mks-viva** [comment]
1. Use STM32 ST-LINK Utility
2. File ->  Open file: Robin_nano35_v13_f4_boot_210615.hex
![image](https://user-images.githubusercontent.com/16629551/133766233-2105a20f-168d-4b40-a5a2-27165b32e646.png)
3. ST-LINK -> printf via SWO viewer - Start
![image](https://user-images.githubusercontent.com/16629551/133766459-6def75e7-376f-4309-88a6-90cab50d5166.png)
4. Target -> Erase chip
5. Target -> Program
![image](https://user-images.githubusercontent.com/16629551/133766606-63bdc9de-360c-40f4-be35-aea89a589c0f.png)
![image](https://user-images.githubusercontent.com/16629551/133766688-cdc2b092-a2a1-4a45-a399-6c4e204f780c.png)

**Comment by Bergateo** [comment]
tried out but this is the error that comes if I hit the "printf via SWO viewer" button...
![error st-link2](https://user-images.githubusercontent.com/67469499/133771582-b9ab146b-d830-4d86-86c7-ece3461fee0f.jpeg)
###

**Comment by mks-viva** [comment]
Have ST link find ?
![image](https://user-images.githubusercontent.com/16629551/133772083-fef2a8cc-4ecf-4719-bf8a-8c4f9e9773b1.png)

**Comment by Bergateo** [comment]
There is just a bunch of numbers, but if I unplug it and reinsert it it show a similar serial code, but just for a few seconds...
You can see it from the last picture, with the error in the utility
I've also tried all the ports on the pc but always with the same results...

**Comment by Bergateo** [comment]
I've tried several configuration on the setting tab but no one can comunicate with the board... Is it possible that the cable that came with the st-link has an inverted pin diagram? (since the connectors are facing in opposite direction?)
All the tests are done with and without the 3.3 pin and with voltage coming through the electric socket.. But no changes in the errors

**Comment by willngton** [comment]
I intentionally "broke" my Robin Nano v1.3 and can confirm above step by step provide by @mks-viva  worked fine, however was only able to fully install Marlin, MKS Firmware got stuck on  Font Lib Updating 100%, images to fallow:

@Bergateo 

_1 - Broke the bootloader
2 - Erase/ Re-flash bootloader with STM-Link 2
3 - Attempt to flash MKS Firmware ( stuck on 100% font lib)
4 - Flashed Marlin (worked fine)_

MKS Firmware ( stuck on 100% font lib)
![photo_2021-09-17_17-01-33](https://user-images.githubusercontent.com/5961905/133853547-564bb3d9-0941-4a09-aba6-1a6844903373.jpg)

**STM32 Link wiring** 
![photo_2021-09-17_17-01-49](https://user-images.githubusercontent.com/5961905/133853363-d095db41-7ca8-465a-b2c7-c02e22601a77.jpg)

![photo_2021-09-17_16-54-10](https://user-images.githubusercontent.com/5961905/133853375-377d49f1-c453-4eb8-8faf-9a0559f93b79.jpg)

**STM Link Connection on widows**
![ROBIN_NANOV1 3](https://user-images.githubusercontent.com/5961905/133853828-efc50e67-6296-4138-adbd-a0ef52c44fa9.png)



MKS firmware (stuck on 100 font, and rebooted)
![photo_2021-09-17_17-03-06](https://user-images.githubusercontent.com/5961905/133853390-fab024b3-a716-4c59-99bf-1d85a210ce54.jpg)

Marlin
![photo_2021-09-17_16-54-10 (2)](https://user-images.githubusercontent.com/5961905/133853403-32b74e17-2e20-4a5d-87cd-a5a94cd47be6.jpg)

**Comment by Bergateo** [comment]
Thank you @willngton for the news! But I'm still not able to connect the st-link on the board correctly since the program doesn't recognize the board... How did you do all the wires connection? Have you look out on the pin used by myself? Have the same configuration? 
i've tried to figure it out by looking at your pictures, but still doesn't connet to target... try to look if my assumption based on your photos, are correct:
(on the left are the pin on st-link, on the right on MKS nano)
pin swclk----pin3
pin swdio----pin1
pin GND-----pin6
pin 3.3v-----pin2
are they right? did you use just 4 wires?

**Comment by willngton** [comment]
> Thank you @willngton for the news! But I'm still not able to connect the st-link on the board correctly since the program doesn't recognize the board... How did you do all the wires connection? Have you look out on the pin used by myself? Have the same configuration?
> i've tried to figure it out by looking at your pictures, but still doesn't connet to target... try to look if my assumption based on your photos, are correct:
> (on the left are the pin on st-link, on the right on MKS nano)
> pin swclk----pin3
> pin swdio----pin1
> pin GND-----pin6
> pin 3.3v-----pin2
> are they right? did you use just 4 wires?

You are correct, that is the wiring I used and no other cables, also no external power only the 3.3 provided by STlink

I could not get it working on linux, had to use a fresh windows 10 installation, several reboots , if it will help, I had to run STMLink as administrator. 

![Selection_845](https://user-images.githubusercontent.com/5961905/133869080-9bbe6a4d-ff9f-4b9c-be31-ea3e2f29d2c0.png)

**Comment by Bergateo** [comment]
> > Thank you @willngton for the news! But I'm still not able to connect the st-link on the board correctly since the program doesn't recognize the board... How did you do all the wires connection? Have you look out on the pin used by myself? Have the same configuration?
> > i've tried to figure it out by looking at your pictures, but still doesn't connet to target... try to look if my assumption based on your photos, are correct:
> > (on the left are the pin on st-link, on the right on MKS nano)
> > pin swclk----pin3
> > pin swdio----pin1
> > pin GND-----pin6
> > pin 3.3v-----pin2
> > are they right? did you use just 4 wires?
> 
> You are correct, that is the wiring I used and no other cables, also no external power only the 3.3 provided by STlink
> 
> I could not get it working on linux, had to use a fresh windows 10 installation, several reboots , if it will help, I had to run STMLink as administrator. 
> 
> ![Selection_845](https://user-images.githubusercontent.com/5961905/133869080-9bbe6a4d-ff9f-4b9c-be31-ea3e2f29d2c0.png)
>  

Unfortunately even with your set up I cannot connect to the target... Tried to reboot windows several times and tried out all the USB ports without results.. I'm suspecting that the problem dipends on the st-link at this point.. I'll send it back and buy a new one (similar to yours) and try again.. If I cannot get it working not even with a new st-link, I think I'll buy a new board to get this pain over...

**Comment by Bergateo** [comment]
@willngton 
@mks-viva 

I finally managed to get it working with a new st-link!!

I'm trying to upload marlin, find out here on the repository, but the screen shows again this screen of uploading 100% and stays stucked...
![IMG_20210921_103224.jpg](https://user-images.githubusercontent.com/67469499/134139313-8bbc092e-9402-4401-9f97-5814df0997ff.jpg)

@willngton can you please share the update files to marlin that you have installed?

**Comment by Bergateo** [comment]
we can close this issue, i've managed to correctly intall marlin to the mother board. thank so much for all the help provided guys!

**Comment by willngton** [comment]
> we can close this issue, i've managed to correctly intall marlin to the mother board. thank so much for all the help provided guys!

Great to hear mate !!!

I am not able to install the FW official provided here, only my one version of Marlin based on lasted bug-fix.

**Comment by WermRolent** [comment]
> we can close this issue, i've managed to correctly intall marlin to the mother board. thank so much for all the help provided guys!

how did you solve the problem?

**Comment by burikella** [comment]
I've succeed to write bootloader, but display stopped working: it wasn't lit up during the programming process and doesn't light up after printer reboot.
Doesn anyone have any idea of what could be wrong and what I could do to troubleshoot this?

**Comment by Bergateo** [comment]
@burikella try to check all the wiring, if everything is rightly plugged (that means to make sure that the flat cable is fully plugged and the pin of the connector fully closed) than it could be a broken screen.

**Comment by Besmozka** [comment]
@burikella I have exactly the same problem :( I did everything according to the instructions and during the first firmware everything went well and the screen lit up. After flashing the bootloader, I inserted an SD card with the firmware and turned on the printer, but the screen did not light up and did not turn on again, even when connected via stlink. Is it enough to change the display or do you need to change the motherboard?

**Comment by Besmozka** [comment]
ok, i'm find my trouble. 
I looked at the name of the board (Robin nano-s 1.3) and selected everything based on the name, but then I looked at the chip and everything became clear to me :) so I chose Robin_nano35_boot_200608.hex and my screen worked!
![1696266409393](https://github.com/makerbase-mks/MKS-Robin-Nano-S-Firmware/assets/65767554/4272cb6e-8573-4366-af20-687ce93348eb)
